site_name: Django Class Documentation
markdown_extensions:
  - pymdownx.superfences
  - attr_list
  - md_in_html

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
